---
- name: Setup Zsh with Oh My Zsh
  hosts: localhost
  become: yes
  tasks:
    - name: Install Zsh
      apt:
        name: zsh
        state: present

    - name: Change default shell to Zsh
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /usr/bin/zsh

    - name: Install git
      apt:
        name: git
        state: present

    - name: Clone Oh My Zsh repository
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "/home/{{ lookup('env', 'USER') }}/.oh-my-zsh"
        version: master
        force: yes
      become: no
      run_once: true

    - name: Create .zshrc file from template
      template:
        src: zshrc.j2
        dest: "/home/{{ lookup('env', 'USER') }}/.zshrc"
      become: no
      run_once: true

    - name: Change ownership of .oh-my-zsh directory
      file:
        path: "/home/{{ lookup('env', 'USER') }}/.oh-my-zsh"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        recurse: yes

    - name: Change ownership of .zshrc file
      file:
        path: "/home/{{ lookup('env', 'USER') }}/.zshrc"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"

