---
- name: Setup Zsh with Oh My Zsh
  hosts: localhost
  become: yes
  tasks:
    - name: Install Zsh
      apt:
        name: zsh
        state: present

    - name: Change default shell to Zsh
      user:
        name: "{{ lookup('env', 'SUDO_USER') | default(ansible_user_id) }}"
        shell: /usr/bin/zsh

    - name: Install git
      apt:
        name: git
        state: present

    - name: Clone Oh My Zsh repository
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
        version: master
        force: yes
      become: no

    - name: Create .zshrc file from template
      template:
        src: zshrc.j2
        dest: "{{ ansible_env.HOME }}/.zshrc"
      become: no

    - name: Change ownership of .oh-my-zsh directory
      file:
        path: "{{ ansible_env.HOME }}/.oh-my-zsh"
        owner: "{{ lookup('env', 'SUDO_USER') | default(ansible_user_id) }}"
        group: "{{ lookup('env', 'SUDO_USER') | default(ansible_user_id) }}"
        recurse: yes

    - name: Change ownership of .zshrc file
      file:
        path: "{{ ansible_env.HOME }}/.zshrc"
        owner: "{{ lookup('env', 'SUDO_USER') | default(ansible_user_id) }}"
        group: "{{ lookup('env', 'SUDO_USER') | default(ansible_user_id) }}"

