---
- name: Install curl
  apt:
    name: curl
    state: present

- name: Download Neovim AppImage
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /usr/local/bin/nvim
    mode: '0755'

- name: Verify Neovim AppImage
  command: /usr/local/bin/nvim --version
  register: nvim_version
  ignore_errors: yes

- name: Extract Neovim AppImage if FUSE is not available
  command: /usr/local/bin/nvim --appimage-extract
  args:
    chdir: /usr/local
  when: nvim_version.stderr is search("libfuse.so.2")
  register: appimage_extract

- name: Move extracted Neovim files to /usr/local/nvim
  command: mv /usr/local/squashfs-root /usr/local/nvim
  when: appimage_extract.changed

- name: Create Neovim symlink if extracted
  file:
    src: /usr/local/nvim/AppRun
    dest: /usr/bin/nvim
    state: link
  when: appimage_extract.changed

- name: Ensure /usr/bin/nvim is a symbolic link to /usr/local/bin/nvim if not extracted
  file:
    src: /usr/local/bin/nvim
    dest: /usr/bin/nvim
    state: link
  when: not appimage_extract.changed

- name: Create Neovim configuration directory
  file:
    path: /home/{{ my_user }}/.config/nvim
    state: directory
    mode: '0755'
    owner: "{{ my_user }}"
    group: "{{ my_user }}"

- name: Download Neovim kickstart configuration
  get_url:
    url: https://raw.githubusercontent.com/nvim-lua/kickstart.nvim/master/init.lua
    dest: /home/{{ my_user }}/.config/nvim/init.lua
    mode: '0644'
    owner: "{{ my_user }}"
    group: "{{ my_user }}"

