---
- name: Setup Zsh with Oh My Zsh
  hosts: localhost
  become: yes
  vars:
    user_name: steven
    user_home: "/home/steven"
  tasks:
    - name: Install Zsh
      apt:
        name: zsh
        state: present
      tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]

    - name: Change shell to zsh
      shell: chsh -s $(which zsh) {{ user_name }}
      tags: *tags_for_zsh_tasks

    - name: Check that the .oh-my-zsh directory exists
      stat:
        path: "{{ user_home }}/.oh-my-zsh"
      register: oh_my_stats
      tags: *tags_for_zsh_tasks

    - name: Oh-My-Zsh
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > {{ user_home }}/.oh-my-installer && chmod +x {{ user_home }}/.oh-my-installer && sudo -u {{ user_name }} {{ user_home }}/.oh-my-installer
      tags: *tags_for_zsh_tasks
      when: oh_my_stats.stat.exists == False

    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "{{ user_home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
      tags: *tags_for_zsh_tasks
      become: yes
      become_user: steven

